# Generated by Django 3.2.16 on 2023-02-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_profile_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='phonenumber',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
