# Generated by Django 3.2.16 on 2023-02-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_login'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login',
            table='LOGIN',
        ),
    ]
